appHost: westeurope.cloudapp.azure.com
authHost: {{ .Values.ingress.hosts.auth.host }}

janus:
  enabled: true
  host: {{ .Values.ingress.hosts.auth.host | quote }}
  certmanagerIssuer:
    name: {{ .Values.ingress.certmanagerissuer | quote }}
    kind: ClusterIssuer

  ingressRoutes:
    - name: traefik-forward-auth
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: {}
        services:
          - name: traefik-forward-auth-service
            port: 4181
        middlewares:
          - name: auth
            namespace: networking
      certificate:
        enabled: true
