name: monitoring
namespace: monitoring
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

project:
  name: monitoring
  sourceRepos:
    - '*'
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc

apps:
  - name: prometheus
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.10
      chart: "prometheus"
      valuesFile: "prometheus.yaml"
  - name: thanos
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.7
      chart: "thanos"
      valuesFile: "thanos.yaml"
  - name: grafana
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.3
      chart: "grafana"
      valuesFile: "grafana.yaml"
  - name: loki
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.0
      chart: "loki-stack"
      valuesFile: "loki.yaml"
  - name: jaeger-operator
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.3
      chart: "jaeger-operator"
      valuesFile: "jaeger-operator.yaml"
