standalonePushgateway:
  enabled: true

prometheus-pushgateway:

  image:
    repository: weaveworks/prom-aggregation-gateway
    tag: master-c4415bbe
    pullPolicy: IfNotPresent

  extraArgs: ["-listen", ":9091"]

  # nodeSelector:
  #   agentpool: monitoring

prometheus:

  serviceAccounts:
    pushgateway:
      create: false

  pushgateway:
    enabled: false

  server:
    ingress:
      enabled: false
    # nodeSelector:
    #   agentpool: monitoring

    extraSecretMounts :
    - name: prometheus-bucket
      secretName: prometheus-bucket

    sidecarContainers:
      - name: thanos-sidecar
        image: thanosio/thanos:main-2021-06-04-ef94b7e6
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        args:     
          - "sidecar"
          - "--debug.name=sidecar"
          - "--log.level=debug"
          - "--grpc-address=0.0.0.0:10901"
          - "--grpc-grace-period=1s"
          - "--http-address=0.0.0.0:10902"
          - "--http-grace-period=1s"
          - "--prometheus.url=http://localhost:9090/"
          - "--tsdb.path=/data"
          - "--objstore.config-file=/etc/objectStorage/object-storage.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
            readOnly: true
          - name: storage-volume
            mountPath: /data
          - name: prometheus-bucket
            mountPath: /etc/objectStorage
            readOnly: true

    

  alertmanager:
    # nodeSelector:
    #   agentpool: monitoring
    ingress:
      enabled: false

  # nodeExporter: 
    # nodeSelector:
    #   agentpool: monitoring