# We're not using the dependency chart since we're interrested in changing the gateway to the prom-aggregation-gateway
# https://github.com/weaveworks/prom-aggregation-gateway
# 
# Which needs a change to the liveness and 
#
# no need for this since the current helm chart used is not a dependency chart
prometheus:

  pushgateway:
    # nodeSelector:
    #   agentpool: monitoring

    ## pushgateway container image
    ##
    image:
      repository: weaveworks/prom-aggregation-gateway
      tag: master-c4415bbe
      pullPolicy: IfNotPresent

    extraArgs: ["-listen", ":9091"]

  server:
    ingress:
      enabled: false
    # nodeSelector:
    #   agentpool: monitoring

    extraVolumeMounts:
    - name: prometheus-bucket
      secret:
        secretName: prometheus-bucket

    sidecarContainers:
      - name: thanos-sidecar
        image: thanosio/thanos:main-2021-06-04-ef94b7e6
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        args:     
          - "sidecar"
          - "--debug.name=sidecar"
          - "--log.level=debug"
          - "--grpc-address=0.0.0.0:10901"
          - "--grpc-grace-period=1s"
          - "--http-address=0.0.0.0:10902"
          - "--http-grace-period=1s"
          - "--prometheus.url=http://localhost:9090/"
          - "--tsdb.path=/data"
          - "--objstore.config-file=/etc/objectStorage/object-storage.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
            readOnly: true
          - name: storage-volume
            mountPath: /data
          - name: prometheus-bucket
            mountPath: /etc/objectStorage
            readOnly: true

    

  alertmanager:
    # nodeSelector:
    #   agentpool: monitoring
    ingress:
      enabled: false

  # nodeExporter: 
    # nodeSelector:
    #   agentpool: monitoring