name: example-guestbook
clusterService: false
namespace: example-guestbook
description: Example-guestbook.
projectName: argowf

project:
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destination: 
    - namespace: argowf
      server: https://kubernetes.default.svc

apps:
  - name: example-guestbook
    source:
      repoURL: "https://github.com/distributed-technologies/example-guestbook.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "example-guestbook.yaml"
