name: example-guestbook
clusterService: false
namespace: example-guestbook
description: Example-guestbook.

project:
  name: example-guestbook
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*' 
  

apps:
  - name: example-guestbook
    source:
      repoURL: "https://github.com/distributed-technologies/example-guestbook.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "example-guestbook.yaml"
