name: loadbalancer
clusterService: true
namespace: loadbalancer
description: MetalLB loadbalancer.
projectName: loadbalancer

project:
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: loadbalancer
    source:
      repoURL: "https://github.com/distributed-technologies/services-loadbalancer.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "loadbalancer.yaml"
