name: networking
clusterService: true
namespace: networking
description: networking services like ingress, cert-manager.


project:
  name: networking
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: nidhogg
      server: https://kubernetes.default.svc

apps:
  - name: ingress
    source:
      repoURL: "https://github.com/Open-Olympus-Project/networking-traefik.git"
      targetRevision: main
      path: traefik
      valuesFile: "ingress.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        match: PathPrefix(`/auth`)
        services:
          - name: traefikauth
            port: 80
        middlewares:
          - name: auth
      
      middlewares:
      - name: auth
        spec: 
          forwardAuth:
            address: https://service-poc.westeurope.cloudapp.azure.com/auth/_oauth
            trustForwardHeader: true
            authResponseHeaders:
              - X-Forwarded-User
      certificate:
        enabled: true
        issuerRef:
          name: letsencrypt-staging
          kind: ClusterIssuer
  - name: cert-manager
    source:
      repoURL: "https://github.com/Open-Olympus-Project/k8s-certmanager.git"
      targetRevision: dependency
      path: cert-manager
      valuesFile: "cert-manager.yaml"
  - name: cert-manager-issuer
    source:
      repoURL: "https://github.com/Open-Olympus-Project/k8s-certmanager.git"
      targetRevision: dependency
      path: cert-manager-issuer
      valuesFile: "cert-manager-issuer.yaml"