# serviceDomain: {{ .Values.fqdn }}

dashboardRoute:
  host: {{ .Values.ingress.host }}

traefik:
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.LoadBalancerResoureGroup | quote }}
      cert-manager.io/cluster-issuer: letsencrypt-prod
    spec:
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}

#  ports:
#    web:
#      nodePort: 32080
#    websecure:
#      nodePort: 32443
