# serviceDomain: {{ .Values.fqdn }}

dashboardRoute:
  host: {{ .Values.ingress.host }}

traefik:
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.LoadBalancerResoureGroup | quote }}
    spec:
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}

  additionalArguments:
  - --entryPoints.web.http.redirections.entryPoint.to: websecure
  - --entryPoints.web.http.redirections.entryPoint.scheme: https

#  ports:
#    web:
#      nodePort: 32080
#    websecure:
#      nodePort: 32443

  logs:
    access:
      enabled: true