services:
{{- range $.Values.ingress.hosts}}
- enabled: true
  namePrefix: {{ .name | quote }}
  type: LoadBalancer
  # Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ $.Values.ingress.LoadBalancerResoureGroup | quote }}

  # Additional annotations for TCP service only
  annotationsTCP: {}
  # Additional annotations for UDP service only
  annotationsUDP: {}
  # Additional service labels (e.g. for filtering Service by custom labels)
  labels:
    host: {{ .host }}
  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec:
    loadBalancerIP: {{ .loadBalancerIP }}
  loadBalancerSourceRanges: []
  externalIPs: []
{{ end }}

traefik:
  deployment:
    enabled: true
    # Can be either Deployment or DaemonSet
    kind: DaemonSet

  ingressClass:
    fallbackApiVersion: "v1"
    enabled: true
    isDefaultClass: true

  logs:
    access:
      enabled: true

  ports:
    web:
      port: 80
    websecure:
      port: 443
  
  additionalArguments:
  - --providers.kubernetesingress
  - --providers.kubernetesingress.ingressclass=traefik2
  - --metrics.prometheus=true
  - --entrypoints.web.http.redirections.entrypoint.to=websecure
  - --entrypoints.web.http.redirections.entrypoint.scheme=https