name: tooling
clusterService: true
namespace: tooling
description: Tooling services Argo WF, Harbor.

project:
  name: tooling
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argowf
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-argo-wf.git"
      targetRevision: dependency
      path: chart
      valuesFile: "argowf.yaml"
  - name: harbor
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-harbor.git"
      targetRevision: dependency
      path: harbor
      valuesFile: "harbor.yaml"
