name: tooling
clusterService: true
namespace: tooling
description: Tooling services Argo WF, Harbor.

project:
  name: tooling
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argowf
    ingressAnnotation: 
      traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress:
      argowf: 
        subDomain: argowf
        path: /
        servicePort: 2746
        serviceName: argowf-server 
    source:
      repoURL: "https://github.com/distributed-technologies/services-argowf.git"
      targetRevision: argowf-dependency
      path: chart
      valuesFile: "argowf.yaml"
  - name: harbor
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-harbor.git"
      targetRevision: dependency
      path: harbor
      valuesFile: "harbor.yaml"
