grafana:
  grafana.ini:
    server:
      #TODO HOST URL
      root_url: https://{{ .Values.ingress.hosts.main.host }}/grafana
    auth.proxy:
      enabled: false
      header_name: X-Forwarded-User
      header_property: email
      auto_sign_up: true
      headers: Name:X-Forwarded-User Email:X-Forwarded-Email
      enable_login_token: false

    auth.basic:
      enabled: false

    auth:
      disable_login_form: true

    users.auto.assign:
      org_role: Admin

    auth.generic_oauth:
      enabled = true
      client_id = 1b976479-a11f-4f1b-a5d8-64259d3b05da
      client_secret = vEvhtr52dUYU6P5IydU2_J~AGd_rW.QT.7
      scopes = openid email profile
      empty_scopes = false
      auth_url = ""https://service-auth-poc.westeurope.cloudapp.azure.com/auth"
      token_url = "https://service-auth-poc.westeurope.cloudapp.azure.com/token"
      allowed_domains = mycompany.com mycompany.org
      allow_sign_up = true
      tls_skip_verify_insecure = true


  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring
          access: proxy
          isDefault: true
          jsonData:
            timeInterval: '1m'
        - name: Loki
          type: loki
          url: http://loki.monitoring:3100
          access: proxy
          isDefault: false
          jsonData:
            timeInterval: '1m'
        # - name: Loki-prod
        #   type: loki
        #   url: https://dp-prod.westeurope.cloudapp.azure.com/loki
        #   access: proxy
        #   isDefault: false
        #   jsonData:
        #     timeInterval: '1m'

janus:
  enabled: true
  host: {{ .Values.ingress.hosts.main.host | quote }}
  certmanagerIssuer:
    name: {{ .Values.ingress.certmanagerissuer | quote }}
    kind: ClusterIssuer

  ingressRoutes:
    - name: grafana
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        match: PathPrefix(`/grafana`)
        services:
          - name: grafana
            port: 80
        middlewares:
          # - name: oauth-errors
          #   namespace: networking
          # - name: oauth-auth
          #   namespace: networking
          - name: auth
            namespace: networking
          - name: grafana-stripprefix
      certificate:
        enabled: true

  middlewares:
    - name: grafana-stripprefix
      spec:
        stripPrefix:
          prefixes:
            - /grafana
