#fqdn: 

# This values is if you want to have the applications as a subdomain.
# ingressDomain: test.domain.com 

# This values is if you want to use paths instead of subdomains.
ingress:
  host: service-poc.westeurope.cloudapp.azure.com
  loadBalancerIP: 20.82.41.255
  LoadBalancerResoureGroup: service-aks-poc

networking:
  enabled: true

  ingress:
    enabled: true

  cert-manager:
    enabled: true

tooling: 
  enabled: true

  argowf:
    enabled: false

  argo-events:
    enabled: false

  harbor:
    enabled: false

  vault:
    enabled: false

monitoring:
  enabled: true

  prometheus:
    enabled: false

  thanos:
    enabled: false
  
  grafana:
    enabled: false
  
  loki:
    enabled: false

  jaeger-operator:
    enabled: false


# The same name as the project - This can be used to disable the whole project and namespace.
example-guestbook:
  enabled: false

  # The same name as one of the apps listed under the project.
  example-guestbook:
    enabled: false