#ingressDomain: dev.garagen

ingress:
  hosts:
  - host: <host1>
    loadBalancerIP: <ip>
  - host: <host2>
    loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <resource_group>
  certmanagerissuer: <cert-manager-issuer>
  # className: ingress-traefik

applications: 
  argo-workflows:         true
  argo-events:            true
  argo-events-setup:      true
  argo-events-github:     true
  argo-events-azure:      true
  cert-manager:           true
  cert-manager-issuer:    true
  external-secrets:       true
  grafana:                true
  harbor:                 false
  ingress:                true
  jaeger-operator:        true
  loki:                   true
  prometheus:             true
  thanos:                 true
  vault:                  true
