scName: poc

ingress:
  hosts:
    main:
      host: <host1>
      loadBalancerIP: <ip>
    auth:
      host: <host2>
      loadBalancerIP: <ip>
    vault:
      host: <host3>
      loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <resource_group>
  certmanagerissuer: <cert-manager-issuer>
  # className: ingress-traefik

applications:
  argo-workflows: true
  argo-events: true
  argo-events-setup: true
  argo-events-github: false
  argo-events-azure: false
  cert-manager: true
  cert-manager-issuer: true
  dex: false
  env-yggdrasil-test: true
  external-secrets: true
  grafana: true
  hephaestus: true
  traefik: true
  traefik-forward-auth: true
  jaeger-operator: true
  loki: true
  minio-operator: true
  oauth2-proxy: false
  prometheus: false
  thanos: true
  vault: true
