#fqdn: 

# This values is if you want to have the applications as a subdomain.
# ingressDomain: test.domain.com 

# This values is if you want to use paths instead of subdomains.
host: testHost.com

ingress:
  enabled: false

tooling: 
  enabled: true

  argowf:
    enabled: false

  harbor:
    enabled: false

monitoring:
  enabled: true

  prometheus:
    enabled: false 

  thanos:
    enabled: false
  
  grafana:
    enabled: false
  
  loki:
    enabled: false

  jaeger-operator:
    enabled: false
