#fqdn: 

# This values is if you want to have the applications as a subdomain.
# ingressDomain: test.domain.com 

# This values is if you want to use paths instead of subdomains.
ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <resource_group>
  certmanagerissuer: <cert-manager-issuer>
  # className: ingress-traefik

  annotations:
    # kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-staging

networking:
  enabled: true

  ingress:
    enabled: true

  cert-manager:
    enabled: true
  
  cert-manager-issuer:
    enabled: true
  
  nidhogg-ingress:
    enabled: true

tooling: 
  enabled: true

  argo-workflows:
    enabled: true

  argo-events:
    enabled: true

  harbor:
    enabled: false

  vault:
    enabled: true

  external-secrets:
    enabled: true

monitoring:
  enabled: true

  prometheus:
    enabled: true

  thanos:
    enabled: false
  
  grafana:
    enabled: true
  
  loki:
    enabled: true

  jaeger-operator:
    enabled: true

# The same name as the project - This can be used to disable the whole project and namespace.
example-guestbook:
  enabled: false

  # The same name as one of the apps listed under the project.
  example-guestbook:
    enabled: false

argo-events-setup:
  enabled: true

  argo-events-setup:
    enabled: true

argo-events-events:
  enabled: true

  argo-events-github:
    enabled: true