#ingressDomain: dev.garagen

#clusterNetworking: 
#  ipRangeStart: 192.168.1.40
  # ipRangeStop is both the ipRangeStop but also the ingress loadBalancerIP
#  ipRangeStop: 192.168.1.49

ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <resource_group>
  certmanagerissuer: <cert-manager-issuer>
  # className: ingress-traefik

  annotations:
    # kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: letsencrypt-staging

applications: 
  argo-workflows:         true
  argo-events:            true
  argo-events-setup:      true
  argo-events-github:     true
  argo-events-azure:      true
  cert-manager:           true
  cert-manager-issuer:    true
  example-guestbook:      false
  external-secrets:       true
  grafana:                true
  harbor:                 true
  harbor-operator:        true
  ingress:                true
  jaeger-operator:        true
  loki:                   true
  minio-operator:         true
  postgres-operator:      true
  prometheus:             true
  redis-operator:         true
  thanos:                 true
  vault:                  true
