#fqdn: 

# This values is if you want to have the applications as a subdomain.
# ingressDomain: test.domain.com 

# This values is if you want to use paths instead of subdomains.
host: testHost.com

networking:
  enabled: true

  ingress:
    enabled: true

  cert-manager:
    enabled: true

tooling: 
  enabled: true

  argowf:
    enabled: true

  argo-events:
    enabled: true

  harbor:
    enabled: true

  vault:
    enabled: true

monitoring:
  enabled: true

  prometheus:
    enabled: true

  thanos:
    enabled: true
  
  grafana:
    enabled: true
  
  loki:
    enabled: true

  jaeger-operator:
    enabled: true
