apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/Open-Olympus-Project/repo-helm.git
      revision: main
      directories:
      - path: repo-helm/charts/prometheus/
  - list:
      elements:
        - values:
{{ .Values.ingress | toYaml | indent 12 }}
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Open-Olympus-Project/repo-helm.git
        targetRevision: main
        path: '{{`{{path}}`}}'
        helm:
          values: |
            {{`{{values}}`}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'