apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/Open-Olympus-Project/yggdrasil-v2.git
      revision: main
      directories:
      - path: service/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Open-Olympus-Project/yggdrasil-v2.git
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'