apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argowf-server
  namespace: tooling
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`service-poc.westeurope.cloudapp.azure.com`) && PathPrefix(`/`)
      priority: 10
      services:
        - name: argo-workflows-server
          port: 2746
    
  tls:
    secretName: default-tls