{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
  {{ $project := $root.Files.Get $path | fromYaml }}
  {{ $projectValues := index $root.Values $project.name }}
  {{ if $projectValues.enabled }}
  {{- range $project.apps }}
    {{ if (index $projectValues .name).enabled }}
    {{- if .ingressRoute }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}-ingress-route
  namespace: {{ $project.namespace }}
spec:
  entryPoints:
{{ .ingressRoute.entryPoints | toYaml | indent 4 }}
  routes:
{{- range .ingressRoute.routes}}
  - kind: {{ .kind }}
    match: Host(`{{ $root.Values.ingress.host }}`) && {{ .match }}
    services:
{{ .services | toYaml | indent 6 }}
    middlewares:
{{ .middlewares | toYaml | indent 6 }}
{{- end }}
  tls:
    secretName: {{ .name }}-tls

{{ range .ingressRoute.middlewares }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $project.namespace }}
spec:
{{ .spec | toYaml | indent 2 }}
{{ end }}

{{ if .ingressRoute.certificate.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
  namespace: {{ $project.namespace }}
spec:
  dnsNames:
    - {{ $root.Values.ingress.host }}
  secretName: {{ .name }}-tls
  {{- with .ingressRoute.certificate.issuerRef }}
  issuerRef:
    name: {{ .name }}
    kind: {{ .kind }}
  {{ end }}
{{ end }}

    {{ end }}
    {{ end }}
  {{ end }}
  {{ end }}
{{ end }}
