{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
  {{ $project := $root.Files.Get $path | fromYaml }}
  {{ if (index $root.Values $project.name).enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $project.namespace }}
  {{- end }}
{{- end }}
