
{{- $root := . -}}
{{- range .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: {{ .description }}

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  destinations:
    - namespace:  {{ .namespace | quote }}
      server: https://kubernetes.default.svc

{{- end }}
