{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
    {{- with $root }}
        {{ $project := .Files.Get $path | fromYaml }}
{{- if $project.projectName }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project.projectName }}
  namespace: {{ $root.Release.Namespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: {{ $project.description }}

  # Allow manifests to deploy from any Git repos
{{- if $project.project }}
  sourceRepos:
  {{- if $project.project.sourceRepos }}
    {{- range $project.project.sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  {{- else }}
    - '*'
  {{- end }}

  destinations:
    - namespace:  {{ $project.namespace | quote }}
      server: {{ $project.project.server }}
  {{- if $project.project.destinations }}
    {{- range $project.project.destinations }}
    - namespace: {{ .namespace | quote }}
      server: {{ .server }}
    {{- end }}
  {{- end }}

    {{- end }}
{{- end }}
{{- end }}
{{- end }}