name: argo-events-setup
clusterService: false
namespace: argo-events
description: Argo events setup

project:
  name: argo-events-setup
  sourceRepos:
    - '*'

apps:
  - name: argo-events-github
    source:
      repoURL: "https://github.com/Open-Olympus-Project/argo-events-setup.git"
      targetRevision: HEAD
      path: events-github
      valuesFile: "argo-events-github.yaml"
