name: argo-events-setup
clusterService: false
namespace: tooling
description: Argo events setup

project:
  name: argo-events-setup
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argo-events-setup
    source:
      repoURL: "https://github.com/Open-Dataplatform/argo-events-setup.git"
      targetRevision: HEAD
      path: setup
      valuesFile: "argo-events-setup.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/argo-events/github/push`)
        services:
          - name: github-eventsource-svc
            port: 12000
      certificate:
        enabled: true
        issuerRef:
          name: letsencrypt-staging
          kind: ClusterIssuer