apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-example
spec:
  destination:
    name: ''
    namespace: guestbook-example
    server: 'https://kubernetes.default.svc'
  source:
    path: chart
    repoURL: 'https://github.com/distributed-technologies/test-deployment-repo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
