---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yggdrasil
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: 'Yggdrasil, the root of it all'
  sourceRepos:
    - '*'
  destinations:
    - namespace:  '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yggdrasil
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yggdrasil
  source:
    repoURL: {{ .Values.yggdrasil.repoURL }}
    targetRevision: {{ .Values.yggdrasil.targetRevision }}
    path: yggdrasil
    helm:
      version: v3
      values: |
        ingress:
          host: {{ .Values.yggdrasil.ingress.host }}
          loadBalancerIP: {{ .Values.yggdrasil.ingress.loadBalancerIP }}
          LoadBalancerResoureGroup: {{ .Values.yggdrasil.ingress.LoadBalancerResoureGroup }}
          certmanagerissuer: {{ .Values.yggdrasil.ingress.certmanagerissuer }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nidhogg
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yggdrasil
  source:
    repoURL: {{ .Values.yggdrasil.repoURL }}
    targetRevision: {{ .Values.yggdrasil.targetRevision }}
    path: nidhogg
    helm:
      version: v3
      values: |
        yggdrasil:
          ingress:
            host: {{ .Values.yggdrasil.ingress.host }}
            loadBalancerIP: {{ .Values.yggdrasil.ingress.loadBalancerIP }}
            LoadBalancerResoureGroup: {{ .Values.yggdrasil.ingress.LoadBalancerResoureGroup }}
            certmanagerissuer: {{ .Values.yggdrasil.ingress.certmanagerissuer }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---
