name: ingress
clusterService: true
namespace: ingress
description: Ingress controller.
apps:
  - name: ingress
    source:
      repoURL: "https://github.com/distributed-technologies/mukube-ingress.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "ingress.yaml"
      skipDryRun: false
