name: ingress
clusterService: true
namespace: ingress
description: Ingress controller.
projectName: ingress

project:
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: ingress
    source:
      repoURL: "https://github.com/distributed-technologies/mukube-ingress.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "ingress.yaml"
