name: prometheus
clusterService: true
namespace: prometheus
description: Prometheus.
apps:
  - name: prometheus
    source:
      repoURL: "https://github.com/banzaicloud/banzai-charts.git"
      targetRevision: HEAD
      path: thanos
      valuesFile: "thanos.yaml"
