name: workflows
clusterService: false
namespace: tooling
description: Argo events setup

project:
  name: tooling
  sourceRepos:
    - '*'

apps:
  - name: hephaestus
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.5
      chart: "hephaestus"
      valuesFile: "hephaestus.yaml"