name: workflows
clusterService: false
namespace: tooling
description: Argo setup

project:
  name: tooling
  sourceRepos:
    - '*'

  destinations:
  - namespace: argo
    server: https://kubernetes.default.svc
  - namespace: heph
    server: https://kubernetes.default.svc


apps:
  - name: hephaestus
    source:
      repoURL: "https://github.com/Open-Olympus-Project/repo-helm.git"
      targetRevision: workflow-helm
      path: "charts/hephaestus"
      valuesFile: "hephaestus.yaml"