name: workflows
clusterService: false
namespace: tooling
description: Argo events setup

project:
  name: tooling
  sourceRepos:
    - '*'

apps:
  - name: hephaestus
    source:
      repoURL: "https://github.com/Open-Olympus-Project/repo-helm.git"
      targetRevision: workflow-helm
      path: "charts/hephaestus"
      valuesFile: "hephaestus.yaml"