name: workflows
clusterService: false
namespace: tooling
description: Argo events setup

project:
  name: tooling
  sourceRepos:
    - '*'

apps:
  - name: hepheastus
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.0
      chart: "hepheastus"
      valuesFile: "hepheastus.yaml"