apiVersion: v2
type: application
name: argo-chart
description: A chart that deploys argo
version: v0.3.4

dependencies:
  - name: argo-cd
    version: "2.17.1"
    repository: "https://argoproj.github.io/argo-helm"
  - name: mukube-vnet
    version: "v0.1.2"
    repository: "https://distributed-technologies.github.io/helm-repository/"
    condition: 'installCNI'
