# A reference to this repo itself.
yggdrasil:
  repoURL: "https://github.com/Open-Olympus-Project/yggdrasil.git"
  targetRevision: "HEAD"

installCNI: false

argo-cd: 
  controller: 
    enableStatefulSet: true
  redis-ha: 
    enabled: true
  server: 
    config:
      repositories: |
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argoproj
        - type: helm
          url: https://distributed-technologies.github.io/helm-repository/
          name: dt-helmrepo
    service: 
      type: NodePort
