nidhogg:
  yggdrasil:
    repoURL: "https://github.com/Open-Olympus-Project/infra-yggdrasil.git"
    targetRevision: "main"
    containerRegistryUrl: serviceacrps.azurecr.io
    ingress:
      LoadBalancerResoureGroup: service-aks-ps
      certmanagerissuer: letsencrypt-prod
      hosts:
        main:
          host: service-ps.westeurope.cloudapp.azure.com # This is what argocd will run on
          loadBalancerIP: 20.93.211.177
        vault:
          host: service-vault-ps.westeurope.cloudapp.azure.com
          loadBalancerIP: 20.93.212.33
        auth:
          host: service-auth-ps.westeurope.cloudapp.azure.com
          loadBalancerIP: 20.103.51.93

  installCNI: false

  argo-cd:
    controller:
      replicas: 3
      env:
        - name: "ARGOCD_CONTROLLER_REPLICAS"
          value: "3"
      enableStatefulSet: true
    redis-ha:
      enabled: true
    redis:
      enabled: false
    server:
      replicas: 3
      extraArgs:
        - --insecure
        - --rootpath
        - /argocd

      rbacConfig:
        policy.default: role:admin

      config:
        url: https://service-ps.westeurope.cloudapp.azure.com/argocd
        repositories: |
          # - type: git
          #   url: https://github.com/Open-Olympus-Project/*

        oidc.config: |
          name: Azure
          issuer: https://login.microsoftonline.com/f7619355-6c67-4100-9a78-1847f30742e2/v2.0
          clientID: 1b976479-a11f-4f1b-a5d8-64259d3b05da
          clientSecret: $argocd-auth-secret:oidc.azure.clientSecret
          requestedIDTokenClaims:
            groups:
              essential: true
          requestedScopes:
            - openid
            - profile
            - email

        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
          admissionregistration.k8s.io/ValidatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
              - /webhooks/0/namespaceSelector/matchExpressions/2
          apiextensions.k8s.io/CustomResourceDefinition:
            ignoreDifferences: |
              jsonPointers:
              - /spec/preserveUnknownFields
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
          jaegertracing.io/Jaeger:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs

    configs:
      secret:
        # createSecret: false
        # This is not a secret password. It is okay to be on github
        argocdServerAdminPassword: $2y$12$m4KC7G9d8NFxInl7GRpQ1OpPPrF43Msa33ZQjj0YmT6f8uwjHW8AO
        argocdServerAdminPasswordMtime: "2021-01-02T15:04:05Z"

argocd-applicationset:
  args:
    namespace: nidhogg
    argocdRepoServer: nidhogg-argocd-repo-server:8081

lethe:
  enabled: true
  secretStores:
    - name: k8s-secret-backend
      providers:
        vault:
          server: "http://vault.tooling.svc:8200"
          path: "k8s"
          version: "v2"
          auth:
            # Authenticate against Vault using a Kubernetes ServiceAccount
            # token stored in a Secret.
            # https://www.vaultproject.io/docs/auth/kubernetes
            kubernetes:
              # Path where the Kubernetes authentication backend is mounted in Vault
              mountPath: "kubernetes"
              # A required field containing the Vault Role to assume.
              role: "k8s-secrets"

  secrets:
    - name: argocd-secret
      secretStore:
        backend: k8s-secret-backend
        kind: SecretStore
      target:
        name: argocd-auth-secret
        template:
          metadata:
            labels:
              app.kubernetes.io/part-of: argocd
      data:
        - secretKey: oidc.azure.clientSecret
          remoteRef:
            key: secrets/sso
            property: clientsecret
