# A reference to this repo itself.
yggdrasil:
  repoURL: "https://github.com/Open-Olympus-Project/yggdrasil.git"
  targetRevision: "mht-app-refactoring"

installCNI: false

argo-cd: 
  controller: 
    enableStatefulSet: true
  redis-ha: 
    enabled: true
  server: 
    config:
      repositories: |
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argoproj
        - type: helm
          url: https://distributed-technologies.github.io/helm-repository/
          name: dt-helmrepo
        - type: helm
          url: https://kubernetes.github.io/kube-state-metrics
          name: metrics
        - type: helm
          url: https://prometheus-community.github.io/helm-charts
          name: node-exporter
        - type: helm
          url: https://grafana.github.io/helm-charts
          name: grafana
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
    service: 
      type: NodePort
