apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: chart
    repoURL: 'https://github.com/distributed-technologies/argo-cd.git'
    targetRevision: move-to-helm-dependencies
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
