name: argowf
clusterService: true
namespace: argowf
description: Argo workflow.
projectName: argowf

project:
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: example-guestbook
      server: https://kubernetes.default.svc

apps:
  - name: argowf
    ingressAnnotation: 
      traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress:
      argowf: 
        host: argowf
        path: /
        servicePort: 2746
        serviceName: argowf-server 
    source:
      repoURL: "https://github.com/distributed-technologies/services-argowf.git"
      targetRevision: argowf-dependency
      path: chart
      valuesFile: "argowf.yaml"
