apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress
  namespace: ingress
spec:
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to ingress
    policies:
    - p, proj:ingress:read-only, applications, get, mukube-ingress/*, allow
    groups:
    - my-oidc-group
