name: env-yggdrasil-test
namespace: nidhogg
description: The yggdrasil instance for test env

project:
  name: env-yggdrasil-test
  sourceRepos:
    - '*'
  destinations:
  - namespace: '*'
    server: https://env-ps-test-129dfade.hcp.westeurope.azmk8s.io:443

apps:
  - name: env-yggdrasil-test
    source:
      repoURL: "https://github.com/Open-Dataplatform/yggdrasil-env.git"
      targetRevision: main
      path: "yggdrasil"
      valuesFile: "yggdrasil-test.yaml"